#-----------------------------------------------------------------------------
# Create counts for main analysis and sensitivity analysis that considers
# the translation path from the target language
#
# It probably would make more sense organizationally to (1) have the
# sensitivity analysis in the gloss sensitivity analysis file, so that
# this file is only the main analysis, or (2) put them all in one file.
# I might do one of these options if I rerun.
#
# Optimization comments:
# 1. Could add a filter ?lang != ?targ. I thought the rows with
#    ?lang = ?targ might be useful for info or debugging but I never look
#    at them. I'll probably do this if I ever rerun the counts.
# 2. Could add a filter at the end to delete the rows where the indicators
#    are always 0. But then ?nSense can't be obtained from count(*). If I
#    move calculation of ?nSense to the first subquery, I still lose the
#    combinations where no records are kept. I could enclose the existing
#    query in OPTIONAL and then join it with the desired 2500
#    combinations, but this requires repeating the subqueries, and I
#    prefer to leave the code simpler. Testing suggested only a ~10% speed
#    improvement and memory use reduction.
#-----------------------------------------------------------------------------

PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?lang ?targ
       (count(*) as ?nSense)
       (sum(?meetsIFTS) as ?nsIFTS)
       (sum(?meetsTransToL2) as ?nsTransToL2)
       (sum(?meetsTrans2ToL2) as ?nsTrans2ToL2)
       (sum(?meetsDemonym) as ?nsDemonym)
       (sum(?meetsPredicateFor) as ?nsPredicateFor)
       (sum(?meetsAny) as ?nsAny)
       (sum(?meetsTransFromL2) as ?nsTransFromL2)
       (sum(?meetsTransOnlyFromL2) as ?nsTransOnlyFromL2)
WHERE {

  { SELECT ?lang (COUNT(*) as ?count)
    WHERE { ?sense ^ontolex:sense / dct:language ?lang }
    GROUP BY ?lang
    ORDER BY DESC(?count)
    LIMIT 50
  }
  { SELECT ?targ (COUNT(*) as ?count2)
    WHERE { ?sense ^ontolex:sense / dct:language ?targ }
    GROUP BY ?targ
    ORDER BY DESC(?count2)
    LIMIT 50
  }

  ?sense a ontolex:LexicalSense ;
         ^ontolex:sense [ dct:language ?lang ] .

  BIND(IF(EXISTS {
       ?sense  wdt:P5137 / ^wdt:P5137 / ^ontolex:sense / dct:language ?targ .
                 }, 1, 0) AS ?meetsIFTS)

  BIND(IF(EXISTS {
       ?sense  wdt:P5972 / ^ontolex:sense / dct:language ?targ .
                 }, 1, 0) AS ?meetsTransToL2)

  BIND(IF(EXISTS {
       ?sense  wdt:P5972 / wdt:P5972? / ^ontolex:sense / dct:language ?targ .
                 }, 1, 0) AS ?meetsTrans2ToL2)

  BIND(IF(EXISTS {
       ?sense  ^wdt:P5972 / ^ontolex:sense / dct:language ?targ .
                 }, 1, 0) AS ?meetsTransFromL2)
  BIND(IF(?meetsTransFromL2 && !?meetsTransToL2, 1, 0) AS ?meetsTransOnlyFromL2)

  BIND(IF(EXISTS {
       ?sense  wdt:P6271 / ^wdt:P6271 / ^ontolex:sense / dct:language ?targ .
                 }, 1, 0) AS ?meetsDemonym)

  BIND(IF(EXISTS {
       ?sense  wdt:P9970 / ^wdt:P9970 / ^ontolex:sense / dct:language ?targ .
                 }, 1, 0) AS ?meetsPredicateFor)

  BIND(IF( ?meetsIFTS = 1    || ?meetsTransToL2 = 1 || ?meetsTrans2ToL2 = 1 ||
           ?meetsDemonym = 1 || ?meetsPredicateFor = 1, 1, 0) AS ?meetsAny)

}
GROUP BY ?lang ?targ
